### ISSUE TITLE
cannot import name urllib

### ISSUE THREAD

**Issue by mu-soliman** [pcmanus/ccm#112]
When trying to initialize CCM on Linux Mint 16, I get the following error:

File "/usr/local/lib/python2.7/dist-packages/ccmlib/repository.py", line 5, in <module>
    from six.moves import urllib
ImportError: cannot import name urllib

**Comment by isokrates** [comment]
Hi, I'm getting this error, and I have six 1.10.0 on Ubuntu 16.04. Why might this be?

**Comment by ptnapoleon** [comment]
@isokrates If you install ccm in a virtualenv, do you still get the same error? What python version are you using?
