### ISSUE TITLE
Exception: Timed out waiting for pid file

### ISSUE THREAD

**Issue by mgobec** [pcmanus/ccm#191]
OS: Windows 7 Professional 64bit
Java: 1.7.0_60 JDK
Python: 2.7.8 June 30. 2014.
PIP: used script from https://pip.pypa.io/en/latest/installing.html
Ant: 1.9.4

Issue description:
Installed ccm with pip install ccm. Received an error:
$ ccm create test -v 2.1.0 -n 3 -s
Current cluster is now: test
Traceback (most recent call last):
  File "c:/Python27/Scripts/ccm", line 72, in <module>
    cmd.run()
  File "c:\Python27\lib\site-packages\ccmlib\cmds\cluster_cmds.py", line 137, in
 run
    if cluster.start(verbose=self.options.debug, wait_for_binary_proto=self.opti
ons.binary_protocol, jvm_args=self.options.jvm_args, profile_options=profile_opt
ions) is None:
  File "c:\Python27\lib\site-packages\ccmlib\cluster.py", line 260, in start
    p = node.start(update_pid=False, jvm_args=jvm_args, profile_options=profile_
options)
  File "c:\Python27\lib\site-packages\ccmlib\node.py", line 459, in start
    self.__clean_win_pid()
  File "c:\Python27\lib\site-packages\ccmlib\node.py", line 1135, in __clean_win
_pid
    raise Exception('Timed out waiting for pid file.')
Exception: Timed out waiting for pid file.

Removed ccm with pip uninstall ccm and pulled from git. Tried running on development branch:
$ python ccm create test -v 2.1.0 -n 3 -s
Current cluster is now: test
Traceback (most recent call last):
  File "ccm", line 72, in <module>
    cmd.run()
  File "c:\development\ccm\ccmlib\cmds\cluster_cmds.py", line 164, in run
    if cluster.start(verbose=self.options.debug, wait_for_binary_proto=self.opti
ons.binary_protocol, jvm_args=self.options.jvm_args, profile_options=profile_opt
ions) is None:
  File "c:\development\ccm\ccmlib\cluster.py", line 249, in start
    p = node.start(update_pid=False, jvm_args=jvm_args, profile_options=profile_
options)
  File "c:\development\ccm\ccmlib\node.py", line 491, in start
    self.__clean_win_pid()
  File "c:\development\ccm\ccmlib\node.py", line 1172, in __clean_win_pid
    raise Exception('Timed out waiting for pid file.')
Exception: Timed out waiting for pid file.

**Comment by LuminusDev** [comment]
Same issue, and set the execution policy to unrestricted not work for me.

**Comment by ptnapoleon** [comment]
I will start work on this bug on Monday. After fixing, it should work whether or not execution policy is set to unrestricted. @LuminusDev, what Cassandra version did you run into this problem with?

**Comment by LuminusDev** [comment]
I tried with 2.0.11, 2.1.0 and 2.1.2.
I installed DataStax Community earlier, and Cassandra worked fine with it (I don't know if it can be useful to know that to understand the bug).
OS : Windows 7 Professional 64bit

**Comment by ptnapoleon** [comment]
Okay the fact that it didn't work with 2.0.11 is very surprising. Setting execution policy would in fact not help with 2.0.11. Unfortunately, the way the code logic works on Windows right now is that "Timed out waiting for pid file" could mean any one of three things:
1. Cassandra started fine via the restricted method, and did not attempt to write the pid file
2. Cassandra started fine via the unrestricted method, but could not write the pid file
3. Cassandra failed to start.

After the fix for this issue, it should be much more obvious what is going wrong. 9/10 times, it is a permission issue or an inability to bind the C* ports.

**Comment by LuminusDev** [comment]
Ok, I will dig in this way to find something I did wrong maybe.

**Comment by ptnapoleon** [comment]
Are you trying to start more than one node via ccm? The fact that DSC worked indicates that at least the normal ports for the first node should work.

**Comment by mgobec** [comment]
Can this be solved by requiring elevated privileges when executing this code on windows ? I know its a horrible paint to support windows and I've been there.

**Comment by ptnapoleon** [comment]
It should not require elevated privileges, though they do help with some of the more common problems. Currently it does require unrestricted powershell execution. I have seen non-admin users have problems shutting C* down.

**Comment by LuminusDev** [comment]
I have the same error with 1 node or 3 nodes. I try to execute Powershell in administrator too. I think I will work on Linux to use ccm, it must be the best solution for me in my situation.

**Comment by ptnapoleon** [comment]
That would probably be best for the time being.

**Comment by LuminusDev** [comment]
In `cluster.conf` I have this lines for `install_dir` : 
```
install_dir: !!binary |
  QzpcVXNlcnNcS+lr6VwuY2NtXHJlcG9zaXRvcnlcMi4xLjI=
```

Is it normal ?

**Comment by ptnapoleon** [comment]
Definitely not. That is supposed to point to a directory.

**Comment by LuminusDev** [comment]
Ok, so I discover my problem. I have an "é" in my path, and it's impossible currently (I try with a space too, it's impossible).
I changed the location of `.ccm` and it works now. So you're right, it is `3. Cassandra failed to start.`

**Comment by ptnapoleon** [comment]
Okay. With the change I have made today, I can now guarantee that if ccm is being run from the `develop` branch, if the time out occurs AND no pid is present if you check manually, then C* just failed to start.

**Comment by ptnapoleon** [comment]
This should make it into a release soon. It will assist in debugging issues as we will no longer be conflating powershell policy problems.

**Comment by Sarrae1406** [comment]
Cassandra version 3.0.0 causing same issue for me :

  File "ccm.py", line 112, in <module>
    cmd.run()
  File "F:\WorkStation\Git\ccm\ccmlib\cmds\cluster_cmds.py", line 511, in run
    if self.cluster.start(no_wait=self.options.no_wait,
  File "F:\WorkStation\Git\ccm\ccmlib\cluster.py", line 524, in start
    p = node.start(update_pid=False, jvm_args=jvm_args, jvm_version=jvm_version,
  File "F:\WorkStation\Git\ccm\ccmlib\node.py", line 878, in start
    self.__clean_win_pid()
  File "F:\WorkStation\Git\ccm\ccmlib\node.py", line 2006, in __clean_win_pid
    raise Exception('Timed out waiting for pid file.')
Exception: Timed out waiting for pid file.
