### ISSUE TITLE
Nodes Look down when they are up - DSE 4.6

### ISSUE THREAD

**Issue by phact** [pcmanus/ccm#193]
To reproduce:

 ccm create dse-4.6 --install-dir=/Users/sebastianestevez/Documents/dse-4.6.0/ --dse -n 2

 ccm start

sestevez-rmbp:Valtanix sebastianestevez$ ccm node1 nodetool status
objc[5434]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Note: Ownership information does not include topology; for complete information, specify a keyspace
Datacenter: Solr

Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens  Owns   Host ID                               Rack
UN  127.0.0.1  107.55 KB  1       50.0%  b6a2d308-f2df-4f8b-af8f-0c35fcebf513  rack1
UN  127.0.0.2  114.85 KB  1       50.0%  1f6daf29-0374-41f9-a7ac-b72081b8f94d  rack1
sestevez-rmbp:Valtanix sebastianestevez$ ccm status
Cluster: 'dse-4.6'

node1: DOWN
node2: DOWN
sestevez-rmbp:Valtanix sebastianestevez$

**Comment by razvanz** [comment]
I get the same exception on OSX 10.10.something. This seems to be a [bug in Java SDK](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8022291).

I haven't found a solution, but I will try to roll back to JDK 1.7.0_25, according to [this stackoverflow thread](http://stackoverflow.com/questions/20794751/class-javalaunchhelper-is-implemented-in-both-one-of-the-two-will-be-used-whic) and see if it's fixed.

**Comment by razvanz** [comment]
PS: I was getting the `Class JavaLaunchHelper is implemented in both ...` error when I was running `ccm start`. Downgrading to  [JDK 1.7.0_25](http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html#jdk-7u25-oth-JPR) stopped producing the error.

**Comment by ptnapoleon** [comment]
@razvanz The `JavaLaunchHelper` error message is a known problem on OSX. It has absolutely no negative effect towards C* or ccm functionality, beyond that error message being printed. It is definitely not worth downgrading to such an old JDK just to avoid the issue. Alternatively, it is also fixed on newer JDK 8 releases.

**Comment by ptnapoleon** [comment]
Also closing this since @phact hasn't responded in a while, and I suspect his original issue is fixed.
