### ISSUE TITLE
Setup Cassandra on multiple machines

### ISSUE THREAD

**Issue by spockz** [pcmanus/ccm#222]
It would be great if we could manage a C* cluster on multiple machines through CCM. This way it would be easy to create a test-setup for testing latency and such.

Probably we can do something if we have ssh access and ccm installed on the remote machines. Did anyone already think to do something like this?

**Comment by ptnapoleon** [comment]
There are plenty of other tools for administering a real Cassandra cluster. Consider using Opscenter. This request is distinctly outside the scope of the project.
