### ISSUE TITLE
Feature request: PAUSE & RESUME

### ISSUE THREAD

**Issue by kishkaru** [pcmanus/ccm#225]
It would be nice to have a feature added to the Python API with the commands `ccm nodeX pause` and `ccm nodeX resume`, or something similar. 

`pause` would do a `kill -SIGSTOP` on the pid of the given node.
`resume` would do a `kill -SIGCONT` on the pid of the given node.

These features are useful in simulating network failures on C* nodes, and thus useful in simulating internal C* server errors. These help trigger errors such as `ReadTimeoutError` and `WriteTimeoutError` which are impossible to trigger on the client-side as any graceful shutdown of nodes will notify the driver/client of down nodes. 

The DataStax ruby-driver is currently doing similar functionality in its tests via modifying iptables, but doing it via CCM would be much nicer.

**Comment by ptnapoleon** [comment]
@kishkaru When you say added to the Python API, do you also want them available as command line options as well? Or should they only be accessible via the Python API?

**Comment by kishkaru** [comment]
@ptnapoleon CLI options as well. Thanks!

**Comment by ptnapoleon** [comment]
Just a warning, after pausing a node, commands such as `ccm node nodetool` will hang indefinitely.

**Comment by kishkaru** [comment]
LGTM :+1:
