### ISSUE TITLE
BUILD FAILED for Cassandra 2.0.12

### ISSUE THREAD

**Issue by tulinski** [pcmanus/ccm#229]
Hello,

I cannot create a cluster with the command:
$ ./ccm create demo_cluster -v 2.0.12

It fails with this error:
gen-cql3-grammar:
     [echo] Building Grammar /home/ulin/.ccm/repository/2.0.12/src/java/org/apache/cassandra/cql3/Cql.g  ...
     [java] error(10):  internal error: Can't get property indirectDelegates using method get/isIndirectDelegates from org.antlr.tool.Grammar instance : java.lang.NullPointerException

**Comment by ptnapoleon** [comment]
What versions of ant and the jdk are you using? As a workaround for now, try using `-v binary:2.0.12`.

**Comment by tulinski** [comment]
This error occurs when using java 8. With java 7 compilation succeeds.

**Comment by ptnapoleon** [comment]
Okay. I don't think java 8 is supported for 2.0, only 2.1, but feel free to file a ticket with Cassandra to see.
