### ISSUE TITLE
Solr nodes bind to all IPs

### ISSUE THREAD

**Issue by jasonmk** [pcmanus/ccm#234]
Using CCM to create a local DSE cluster.  It appears that if I create a cluster of all solr nodes, then the first one to start up binds to *:8983 and receives all requests.  The rest of the solr instances aren't accessible.  I tried to find where the configuration is for tomcat, but everything in the server.xml file appears to be commented out, so I'm not sure where it's coming from.

**Comment by ptnapoleon** [comment]
@mike-tr-adamson Is Solr binding to 0.0.0.0 here? If so, is there anything we can do about it?

**Comment by mike-tr-adamson** [comment]
I've spoken to the search team and they reckon it's probably tomcat. If it
is then that's fixable. Unfortunately I'm on holiday for a week so won't be
able to look at it till I get back.

**Comment by jasonmk** [comment]
Any movement on this?

**Comment by mike-tr-adamson** [comment]
@jasonmk I've just raised a PR to fix this which I believe has just been merged.

**Comment by ptnapoleon** [comment]
@jasonmk Let me know if Mike's PR fixed your issue. It has been merged to master, but is not in a release on PyPI yet.

**Comment by jasonmk** [comment]
Looks great, thanks!
