### ISSUE TITLE
Use `nodetool info` in Node.data_size

### ISSUE THREAD

**Issue by mambocab** [pcmanus/ccm#244]
The existing implementation just reads the sizes of files on disk. It should use `nodetool` for this instead. More discussion on these dtest issues/PRs:

https://github.com/riptano/cassandra-dtest/issues/190
https://github.com/riptano/cassandra-dtest/issues/182
https://github.com/riptano/cassandra-dtest/issues/184

**Comment by mambocab** [comment]
I have an implementation that's been added to the dtests as a helper method, which I'll improve and make a PR with if there are no objections to this change.

**Comment by ptnapoleon** [comment]
Not only not objected, but desired.

**Comment by ptnapoleon** [comment]
Fixed by #247
