### ISSUE TITLE
Create cmd with start and binary protocol flag returns before binary protocol started

### ISSUE THREAD

**Issue by jorgebay** [pcmanus/ccm#248]
I've been experiencing on driver our integration tests since updated to the latest 2.0.3 version.
The driver test harness executes a create-and-run command and it returns before the binary protocol started.

I've created a python script that simulates what we are doing on the C# driver test harness:
```python
import os, socket, time
os.system("ccm create test -n 1 -s -i 127.0.0. -b -v 2.1.3")
# time.sleep(1)
sock = socket.socket()
sock.connect(("127.0.0.1", 9042))
sock.close()
```

**Comment by ptnapoleon** [comment]
Is it enough to use the existing flag `--wait-for-binary-proto` in `ccm start` and simple break your ccm command up into two arguments? If not, I can move `--wait-for-binary-proto` into `ccm create` as well.

**Comment by jorgebay** [comment]
I will split back into create, populate and start. But it could be great if you could add  `--wait-for-binary-proto` option in the future for the create cmd.

**Comment by jorgebay** [comment]
It looks like it is not related to the `wait_for_binary_proto` value, as [it is being assigned as `true`](binary_protocol) in this case.

It looks like it is related to the waiting for the log on Windows with C* 2.1, as the `watch_for_log` [returns early due to the process exit](https://github.com/pcmanus/ccm/blob/master/ccmlib/node.py#L383).
