### ISSUE TITLE
Unavailable exception : on any request towards a new table

### ISSUE THREAD

**Issue by flarcher** [pcmanus/ccm#263]
I use the latest CCM from github
I use the `cqlsh` provided with the version 2.1.0 of C*
```
$ ccm create -n3 -v2.1.0 test5
$ ccm start
$ ccm node2 show
node2: UP
       cluster=test5
       auto_bootstrap=False
       thrift=('127.0.0.2', 9160)
       binary=('127.0.0.2', 9042)
       storage=('127.0.0.2', 7000)
       jmx_port=7200
       remote_debug_port=0
       initial_token=-3074457345618258603
       pid=4664
$ cqlsh 127.0.0.2
Connected to test5 at 127.0.0.2:9042.
[cqlsh 5.0.1 | Cassandra 2.1.0-SNAPSHOT | CQL spec 3.2.0 | Native protocol v3]
Use HELP for help.
cqlsh> desc keyspaces;

system_traces  system

cqlsh> use system;
cqlsh:system> select * from paxos limit 2;

(0 rows)
```
Until now : everything looks fine

Then, I start my application that uses the CCManaged new C* cluster ;  it creates some C* tables using `CREATE TABLE IF NOT EXISTS`   and when it tries to prepare statements on them, it gets :
`com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency LOCAL_QUORUM (1 required but only 0 alive)`

I also get the issue with cqlsh ;
```
cqlsh> use main;
cqlsh:main> select * from user limit 2;
Traceback (most recent call last):
  File "/home/fabrice/tools/cassandra/bin/cqlsh", line 909, in perform_simple_statement
    rows = self.session.execute(statement, trace=self.tracing_enabled)
  File "/home/fabrice/tools/apache-cassandra-2.1.0/bin/../lib/cassandra-driver-internal-only-2.1.0.post.zip/cassandra-driver-2.1.0.post/cassandra/cluster.py", line 1281, in execute
    result = future.result(timeout)
  File "/home/fabrice/tools/apache-cassandra-2.1.0/bin/../lib/cassandra-driver-internal-only-2.1.0.post.zip/cassandra-driver-2.1.0.post/cassandra/cluster.py", line 2772, in result
    raise self._final_exception
Unavailable: code=1000 [Unavailable exception] message="Cannot achieve consistency level ONE" info={'required_replicas': 1, 'alive_replicas': 0, 'consistency': 1}
cqlsh:main> quit
```
But the C* cluster is still UP
```
$ ccm status
Cluster: 'test5'
----------------
node1: UP
node3: UP
node2: UP
$ ccm node2 nodetool status
Note: Ownership information does not include topology; for complete information, specify a keyspace
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens  Owns    Host ID                               Rack
UN  127.0.0.1  1.08 MB    1       33.3%   3bfe8d61-a173-4389-b2c6-796e619f9206  rack1
UN  127.0.0.2  1.01 MB    1       33.3%   682863b3-305e-406e-bec8-801734aebf89  rack1
UN  127.0.0.3  1.05 MB    1       33.3%   67a1d3bf-09d1-42d8-8d9a-f3e99a2decee  rack1
```
The issue does not appear with a *classic* C* instance (without CCM)

**Comment by ptnapoleon** [comment]
Can you paste the schema of the keyspace you are trying to create the table in?

**Comment by flarcher** [comment]
**I solved it** ; I should have checked the difference between the configuration of my local *classic* C* with the configuration of CCManaged nodes :disappointed_relieved: 

Here is the CQL description of the keyspace ;
```
CREATE KEYSPACE main WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '3'}  AND durable_writes = true;
```
And I realized that the configuration of nodes is using a *SimpleSnitch*. Then I modified `cassandra-topology.properties` with :
```
# Cassandra Node IP=Data Center:Rack
127.0.0.1=DC1:RAC1
127.0.0.2=DC1:RAC1
127.0.0.3=DC1:RAC1
```
and `cassandra.yaml` with `endpoint_snitch: PropertyFileSnitch`.

It is now working fine :+1:

**Comment by ptnapoleon** [comment]
If you had set the DC value in your keyspace to `datacenter1` instead of `DC1`, it also would have worked. The issue is it looks for nodes who are in "DC1", but there are none, your only DC was `datacenter1`. It's a mistake I've made plenty of times before.

**Comment by dopgm** [comment]
@ptnapoleon  is correct.
If you'll run ccm node1 ring, you'll see a "Datacenter: datacenter1" line above the list of your nodes.
