### ISSUE TITLE
Possible to test a cluster's upgrade ?

### ISSUE THREAD

**Issue by flarcher** [pcmanus/ccm#267]
Hello,

This is rather a question or a feature's request.

I would like to test the behavior of my application during the process of upgrading the C* version on my local C* cluster. In my exemple, I would like to test an upgrade from 2.1.0 to 2.1.4 of the _node2_ only.

I did not see a way to upgrade a node of the cluster using *CCM*. Is there already a way to achieve that ?

Here are the steps of my attempt ;
* I set `install_dir: ~/.ccm/repository/2.1.4` in file `~/.ccm/cluster/node2/node.conf`. Others nodes still use a version 2.1.0.
* I also modified the version of _jamm_ in file `~/.ccm/cluster/node2/conf/cassandra-env.sh` (in order to solve the dependency change to 0.3.0)
* I started the nodes with `ccm start --verbose` ; All nodes expect _node2_ were UP. The output about the start of _node2_ looks fine without any error. But the corresponding C* process in absent (`jps` shows only the C* processes of other nodes) as if it were killed just after the _start_. 

Do you know a workaround or a process than would start an upgraded node (while others are still using an older version of C*) ?

Many thanks,

**Comment by ptnapoleon** [comment]
github.com/riptano/cassandra-dtest tests upgrading Cassandra through CCM. The full process involves

1. Start your entire cluster at 2.1.0
1. Stop the node you want to upgrade
1. Use the `node setdir` command to change the install version or directory of the node to be upgraded
1. Start the upgraded node.

**Comment by flarcher** [comment]
Thanks a lot, it works fine with the command `setdir`.

Here are my commands as an example ;
```
ccm create -n3 -v2.1.0 test
ccm start
ccm node2 stop
ccm node2 setdir -v2.1.4
ccm node2 start
...
```
