### ISSUE TITLE
stress not working with vnodes (works without vnodes) on mac OSX 10.10.3

### ISSUE THREAD

**Issue by dbwrangler** [pcmanus/ccm#310]
Hi

Trying to get cassandra-stress working with ccm vnodes but get error: 

ccm node1 stress
/Users/p/.ccm/repository/2.0.9/tools/bin/cassandra-stress: line 45: /Library/Internet: No such file or directory

It could be me :)

Test:

ps-MacBook-Pro:~ p$ ccm status
Cluster: 'dse_cluster'
----------------------
node1: DOWN
node3: DOWN
node2: DOWN

ps-MacBook-Pro:~ p$ ccm start

ps-MacBook-Pro:~ p$ ccm status
Cluster: 'dse_cluster'
----------------------
node1: UP
node3: UP
node2: UP
ps-MacBook-Pro:~ p$ ccm node1 nodetool status
Note: Ownership information does not include topology; for complete information, specify a keyspace
Datacenter: Cassandra
=====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens  Owns   Host ID                               Rack
UN  127.0.0.1  192.94 MB  1       33.3%  c6693f4f-0e4a-411f-a618-33948e0b6d07  rack1
UN  127.0.0.2  192.23 MB  1       33.3%  2f2d9999-b100-45f2-a7a0-8044ae27a89d  rack1
UN  127.0.0.3  192.57 MB  1       33.3%  9fddb72d-89ab-41ef-afb8-0c6e478d579c  rack1
ps-MacBook-Pro:~ p$
ps-MacBook-Pro:~ p$ ccm node1 stress

15/06/21 10:43:09 INFO snitch.Workload: Setting my workload to Cassandra
Unable to create stress keyspace: Keyspace names must be case-insensitively unique ("Keyspace1" conflicts with "Keyspace1")
total,interval_op_rate,interval_key_rate,latency,95th,99.9th,elapsed_time
39548,3954,3954,5.0,45.6,129.7,10
90366,5081,5081,4.0,40.4,155.7,20
133289,4292,4292,3.6,40.3,233.6,30
192237,5894,5894,3.7,37.8,197.5,41
243726,5148,5148,3.4,35.6,197.7,51
309298,6557,6557,3.4,33.6,197.7,61
377081,6778,6778,3.3,30.0,197.5,71
430227,5314,5314,3.1,29.4,197.5,82
489522,5929,5929,3.1,28.6,196.9,92
558546,6902,6902,3.0,29.4,196.9,102
619152,6060,6060,2.9,28.8,197.2,112
689209,7005,7005,2.6,26.7,246.2,123
762541,7333,7333,2.7,23.1,246.2,133
841041,7850,7850,2.7,22.6,196.8,143
909313,6827,6827,2.7,23.1,196.8,153
980124,7081,7081,2.7,22.2,196.5,164
1000000,1987,1987,2.7,22.4,196.5,168

Averages from the middle 80% of values:
interval_op_rate          : 6255
interval_key_rate         : 6255
latency median            : 3.1
latency 95th percentile   : 30.5
latency 99.9th percentile : 208.5
Total operation time      : 00:02:48
END
ps-MacBook-Pro:~ p$ ccm stop
ps-MacBook-Pro:~ p$
ps-MacBook-Pro:~ p$ ccm switch dse_cluster_vnodes
ps-MacBook-Pro:~ p$ ccm start

ps-MacBook-Pro:~ p$ ccm node1 nodetool status

Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens  Owns (effective)  Host ID                               Rack
UN  127.0.0.1  70.36 KB   256     68.1%             74bc9cd6-114b-4c96-ab8b-2373924b0903  rack1
UN  127.0.0.2  70.42 KB   256     70.9%             cea3f47a-7a1e-4e04-9884-ca820494967a  rack1
UN  127.0.0.3  70.35 KB   256     60.9%             58f96c9f-be84-4d47-89c9-9443ff01c685  rack1
ps-MacBook-Pro:~ p$ ccm node1 stress
/Users/p/.ccm/repository/2.0.9/tools/bin/cassandra-stress: line 45: /Library/Internet: No such file or directory
ps-MacBook-Pro:~ p$ ls /Library/Internet
ls: /Library/Internet: No such file or directory
ps-MacBook-Pro:~ p$ ls /Library/Internet\ Plug-Ins/
AdobeAAMDetect.plugin			Quartz Composer.webplugin
AdobePDFViewer.plugin			QuickTime Plug...
....

**Comment by ptnapoleon** [comment]
Could you list the commands you used to create those clusters?

**Comment by dbwrangler** [comment]
Your suspicion was right... 

ccm create dse_cluster --dse -n 3  -v 4.6.7
ccm create dse_cluster_vnodes  -n 3  -v 2.0.9 --vnodes

When I create with:
ccm create dse_cluster_vnodes2 --dse -n 3  -v 4.6.7 --vnodes

'ccm node1 stress'  works fine.

That said, v 2.0.9 should be stressable, but I'm not going to get stressed about it.

Thanks!

**Comment by ptnapoleon** [comment]
I was able to stress 2.0.9. Perhaps something is wrong with your 2.0.9 install? Try deleting ~/.ccm/repository/2.0.9.  You could also try installing with `-v binary:2.0.9`

**Comment by dbwrangler** [comment]
Thanks!
