### ISSUE TITLE
failed to create clusters with ccm

### ISSUE THREAD

**Issue by davidzhang2013** [pcmanus/ccm#317]
Hello, I believe I followed the instruction from: https://pypi.python.org/pypi/ccm/2.0.4
Here is what I have with CentOS 7:
$ java -version
openjdk version "1.8.0_45"
OpenJDK Runtime Environment (build 1.8.0_45-b13)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)

$ ant -version
Apache Ant(TM) version 1.9.5 compiled on May 31 2015

pyYAML is installed
six lib is installed
Python 2.7.5  is installed
Apache Maven 3.3.3 is installed

cassandra 2.0.16 is running on my local machine.

When I ran the following command:
ccm create test -v 2.0.5
I got the following errors (actually, no matter what versions):

Buildfile: /root/.ccm/repository/2.0.5/build.xml

init:
    [mkdir] Created dir: /root/.ccm/repository/2.0.5/build/classes/main
    [mkdir] Created dir: /root/.ccm/repository/2.0.5/build/classes/thrift
    [mkdir] Created dir: /root/.ccm/repository/2.0.5/build/test/lib
    [mkdir] Created dir: /root/.ccm/repository/2.0.5/build/test/classes
    [mkdir] Created dir: /root/.ccm/repository/2.0.5/src/gen-java
    [mkdir] Created dir: /root/.ccm/repository/2.0.5/build/lib

maven-ant-tasks-localrepo:

maven-ant-tasks-download:
     [echo] Downloading Maven ANT Tasks...
      [get] Getting: http://repo2.maven.org/maven2/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar
      [get] To: /root/.ccm/repository/2.0.5/build/maven-ant-tasks-2.1.3.jar

maven-ant-tasks-init:

maven-declare-dependencies:

maven-ant-tasks-retrieve-build:
[artifact:dependencies] Downloading: org/apache/rat/apache-rat/0.6/apache-rat-0.6-sources.jar from repository central at http:
//repo1.maven.org/maven2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'org.apache.rat:apache-rat:java-source:sources:0.6' in repository centr
al (http://repo1.maven.org/maven2)
[artifact:dependencies] Downloading: org/apache/rat/apache-rat/0.6/apache-rat-0.6-sources.jar from repository apache at https:
//repository.apache.org/content/repositories/releases
[artifact:dependencies] Error transferring file: java.lang.RuntimeException: Could not generate DH keypair
[artifact:dependencies] [WARNING] Unable to get resource 'org.apache.rat:apache-rat:java-source:sources:0.6' from repository a
pache (https://repository.apache.org/content/repositories/releases): Error transferring file: java.lang.RuntimeException: Coul
d not generate DH keypair
[artifact:dependencies] Downloading: org/apache/rat/apache-rat/0.6/apache-rat-0.6-sources.jar from repository java.net2 at htt
p://download.java.net/maven/2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'org.apache.rat:apache-rat:java-source:sources:0.6' in repository java.
net2 (http://download.java.net/maven/2)
[artifact:dependencies] Downloading: org/apache/hadoop/hadoop-core/1.0.3/hadoop-core-1.0.3-sources.jar from repository central
 at http://repo1.maven.org/maven2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'org.apache.hadoop:hadoop-core:java-source:sources:1.0.3' in repository
 central (http://repo1.maven.org/maven2)
[artifact:dependencies] Downloading: org/apache/hadoop/hadoop-core/1.0.3/hadoop-core-1.0.3-sources.jar from repository apache
at https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Error transferring file: java.lang.RuntimeException: Could not generate DH keypair
[artifact:dependencies] [WARNING] Unable to get resource 'org.apache.hadoop:hadoop-core:java-source:sources:1.0.3' from reposi
tory apache (https://repository.apache.org/content/repositories/releases): Error transferring file: java.lang.RuntimeException
: Could not generate DH keypair
[artifact:dependencies] Downloading: org/apache/hadoop/hadoop-core/1.0.3/hadoop-core-1.0.3-sources.jar from repository java.ne
t2 at http://download.java.net/maven/2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'org.apache.hadoop:hadoop-core:java-source:sources:1.0.3' in repository
 java.net2 (http://download.java.net/maven/2)
[artifact:dependencies] Downloading: xmlenc/xmlenc/0.52/xmlenc-0.52-sources.jar from repository central at http://repo1.maven.
org/maven2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'xmlenc:xmlenc:java-source:sources:0.52' in repository central (http://
repo1.maven.org/maven2)
[artifact:dependencies] Downloading: xmlenc/xmlenc/0.52/xmlenc-0.52-sources.jar from repository apache at https://repository.a
pache.org/content/repositories/releases
[artifact:dependencies] Error transferring file: java.lang.RuntimeException: Could not generate DH keypair
[artifact:dependencies] [WARNING] Unable to get resource 'xmlenc:xmlenc:java-source:sources:0.52' from repository apache (http
s://repository.apache.org/content/repositories/releases): Error transferring file: java.lang.RuntimeException: Could not gener
ate DH keypair
[artifact:dependencies] Downloading: xmlenc/xmlenc/0.52/xmlenc-0.52-sources.jar from repository java.net2 at http://download.j
ava.net/maven/2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'xmlenc:xmlenc:java-source:sources:0.52' in repository java.net2 (http:
//download.java.net/maven/2)
[artifact:dependencies] Downloading: commons-beanutils/commons-beanutils-core/1.8.0/commons-beanutils-core-1.8.0-sources.jar f
rom repository central at http://repo1.maven.org/maven2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'commons-beanutils:commons-beanutils-core:java-source:sources:1.8.0' in
 repository central (http://repo1.maven.org/maven2)
[artifact:dependencies] Downloading: commons-beanutils/commons-beanutils-core/1.8.0/commons-beanutils-core-1.8.0-sources.jar f
rom repository apache at https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Error transferring file: java.lang.RuntimeException: Could not generate DH keypair
[artifact:dependencies] [WARNING] Unable to get resource 'commons-beanutils:commons-beanutils-core:java-source:sources:1.8.0'
from repository apache (https://repository.apache.org/content/repositories/releases): Error transferring file: java.lang.Runti
meException: Could not generate DH keypair
[artifact:dependencies] Downloading: commons-beanutils/commons-beanutils-core/1.8.0/commons-beanutils-core-1.8.0-sources.jar f
rom repository java.net2 at http://download.java.net/maven/2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'commons-beanutils:commons-beanutils-core:java-source:sources:1.8.0' in
 repository java.net2 (http://download.java.net/maven/2)
[artifact:dependencies] Downloading: tomcat/jasper-runtime/5.5.12/jasper-runtime-5.5.12-sources.jar from repository central at
 http://repo1.maven.org/maven2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'tomcat:jasper-runtime:java-source:sources:5.5.12' in repository centra
l (http://repo1.maven.org/maven2)
[artifact:dependencies] Downloading: tomcat/jasper-runtime/5.5.12/jasper-runtime-5.5.12-sources.jar from repository apache at
https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Error transferring file: java.lang.RuntimeException: Could not generate DH keypair
[artifact:dependencies] [WARNING] Unable to get resource 'tomcat:jasper-runtime:java-source:sources:5.5.12' from repository ap
ache (https://repository.apache.org/content/repositories/releases): Error transferring file: java.lang.RuntimeException: Could
 not generate DH keypair
[artifact:dependencies] Downloading: tomcat/jasper-runtime/5.5.12/jasper-runtime-5.5.12-sources.jar from repository java.net2
at http://download.java.net/maven/2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'tomcat:jasper-runtime:java-source:sources:5.5.12' in repository java.n
et2 (http://download.java.net/maven/2)
[artifact:dependencies] Downloading: tomcat/jasper-compiler/5.5.12/jasper-compiler-5.5.12-sources.jar from repository central
at http://repo1.maven.org/maven2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'tomcat:jasper-compiler:java-source:sources:5.5.12' in repository centr
al (http://repo1.maven.org/maven2)
[artifact:dependencies] Downloading: tomcat/jasper-compiler/5.5.12/jasper-compiler-5.5.12-sources.jar from repository apache a
t https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Error transferring file: java.lang.RuntimeException: Could not generate DH keypair
[artifact:dependencies] [WARNING] Unable to get resource 'tomcat:jasper-compiler:java-source:sources:5.5.12' from repository a
pache (https://repository.apache.org/content/repositories/releases): Error transferring file: java.lang.RuntimeException: Coul
d not generate DH keypair
[artifact:dependencies] Downloading: tomcat/jasper-compiler/5.5.12/jasper-compiler-5.5.12-sources.jar from repository java.net
2 at http://download.java.net/maven/2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'tomcat:jasper-compiler:java-source:sources:5.5.12' in repository java.
net2 (http://download.java.net/maven/2)
[artifact:dependencies] Downloading: org/eclipse/jdt/core/3.1.1/core-3.1.1-sources.jar from repository central at http://repo1
.maven.org/maven2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'org.eclipse.jdt:core:java-source:sources:3.1.1' in repository central
(http://repo1.maven.org/maven2)
[artifact:dependencies] Downloading: org/eclipse/jdt/core/3.1.1/core-3.1.1-sources.jar from repository apache at https://repos
itory.apache.org/content/repositories/releases
[artifact:dependencies] Error transferring file: java.lang.RuntimeException: Could not generate DH keypair
[artifact:dependencies] [WARNING] Unable to get resource 'org.eclipse.jdt:core:java-source:sources:3.1.1' from repository apac
he (https://repository.apache.org/content/repositories/releases): Error transferring file: java.lang.RuntimeException: Could n
ot generate DH keypair
[artifact:dependencies] Downloading: org/eclipse/jdt/core/3.1.1/core-3.1.1-sources.jar from repository java.net2 at http://dow
nload.java.net/maven/2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'org.eclipse.jdt:core:java-source:sources:3.1.1' in repository java.net
2 (http://download.java.net/maven/2)
[artifact:dependencies] Downloading: net/sf/kosmosfs/kfs/0.3/kfs-0.3-sources.jar from repository central at http://repo1.maven
.org/maven2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'net.sf.kosmosfs:kfs:java-source:sources:0.3' in repository central (ht
tp://repo1.maven.org/maven2)
[artifact:dependencies] Downloading: net/sf/kosmosfs/kfs/0.3/kfs-0.3-sources.jar from repository apache at https://repository.
apache.org/content/repositories/releases
[artifact:dependencies] Error transferring file: java.lang.RuntimeException: Could not generate DH keypair
[artifact:dependencies] [WARNING] Unable to get resource 'net.sf.kosmosfs:kfs:java-source:sources:0.3' from repository apache
(https://repository.apache.org/content/repositories/releases): Error transferring file: java.lang.RuntimeException: Could not
generate DH keypair
[artifact:dependencies] Downloading: net/sf/kosmosfs/kfs/0.3/kfs-0.3-sources.jar from repository java.net2 at http://download.
java.net/maven/2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'net.sf.kosmosfs:kfs:java-source:sources:0.3' in repository java.net2 (
http://download.java.net/maven/2)
[artifact:dependencies] Downloading: hsqldb/hsqldb/1.8.0.10/hsqldb-1.8.0.10-sources.jar from repository central at http://repo
1.maven.org/maven2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'hsqldb:hsqldb:java-source:sources:1.8.0.10' in repository central (htt
p://repo1.maven.org/maven2)
[artifact:dependencies] Downloading: hsqldb/hsqldb/1.8.0.10/hsqldb-1.8.0.10-sources.jar from repository apache at https://repo
sitory.apache.org/content/repositories/releases
[artifact:dependencies] Error transferring file: java.lang.RuntimeException: Could not generate DH keypair
[artifact:dependencies] [WARNING] Unable to get resource 'hsqldb:hsqldb:java-source:sources:1.8.0.10' from repository apache (
https://repository.apache.org/content/repositories/releases): Error transferring file: java.lang.RuntimeException: Could not g
enerate DH keypair
[artifact:dependencies] Downloading: hsqldb/hsqldb/1.8.0.10/hsqldb-1.8.0.10-sources.jar from repository java.net2 at http://do
wnload.java.net/maven/2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'hsqldb:hsqldb:java-source:sources:1.8.0.10' in repository java.net2 (h
ttp://download.java.net/maven/2)
[artifact:dependencies] Downloading: org/apache/hadoop/hadoop-minicluster/1.0.3/hadoop-minicluster-1.0.3-sources.jar from repo
sitory central at http://repo1.maven.org/maven2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'org.apache.hadoop:hadoop-minicluster:java-source:sources:1.0.3' in rep
ository central (http://repo1.maven.org/maven2)
[artifact:dependencies] Downloading: org/apache/hadoop/hadoop-minicluster/1.0.3/hadoop-minicluster-1.0.3-sources.jar from repo
sitory apache at https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Error transferring file: java.lang.RuntimeException: Could not generate DH keypair
[artifact:dependencies] [WARNING] Unable to get resource 'org.apache.hadoop:hadoop-minicluster:java-source:sources:1.0.3' from
 repository apache (https://repository.apache.org/content/repositories/releases): Error transferring file: java.lang.RuntimeEx
ception: Could not generate DH keypair
[artifact:dependencies] Downloading: org/apache/hadoop/hadoop-minicluster/1.0.3/hadoop-minicluster-1.0.3-sources.jar from repo
sitory java.net2 at http://download.java.net/maven/2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'org.apache.hadoop:hadoop-minicluster:java-source:sources:1.0.3' in rep
ository java.net2 (http://download.java.net/maven/2)
[artifact:dependencies] Downloading: org/apache/hadoop/hadoop-test/1.0.3/hadoop-test-1.0.3-sources.jar from repository central
 at http://repo1.maven.org/maven2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'org.apache.hadoop:hadoop-test:java-source:sources:1.0.3' in repository
 central (http://repo1.maven.org/maven2)
[artifact:dependencies] Downloading: org/apache/hadoop/hadoop-test/1.0.3/hadoop-test-1.0.3-sources.jar from repository apache
at https://repository.apache.org/content/repositories/releases
[artifact:dependencies] Error transferring file: java.lang.RuntimeException: Could not generate DH keypair
[artifact:dependencies] [WARNING] Unable to get resource 'org.apache.hadoop:hadoop-test:java-source:sources:1.0.3' from reposi
tory apache (https://repository.apache.org/content/repositories/releases): Error transferring file: java.lang.RuntimeException
: Could not generate DH keypair
[artifact:dependencies] Downloading: org/apache/hadoop/hadoop-test/1.0.3/hadoop-test-1.0.3-sources.jar from repository java.ne
t2 at http://download.java.net/maven/2
[artifact:dependencies] Unable to locate resource in repository
[artifact:dependencies] [INFO] Unable to find resource 'org.apache.hadoop:hadoop-test:java-source:sources:1.0.3' in repository
 java.net2 (http://download.java.net/maven/2)
[artifact:dependencies] Building ant file: /root/.ccm/repository/2.0.5/build/build-dependencies.xml
     [copy] Copying 53 files to /root/.ccm/repository/2.0.5/build/lib/jars
     [copy] Copying 42 files to /root/.ccm/repository/2.0.5/build/lib/sources

check-gen-cli-grammar:

gen-cli-grammar:
     [echo] Building Grammar /root/.ccm/repository/2.0.5/src/java/org/apache/cassandra/cli/Cli.g  ....
     [java] error(10):  internal error: Can't get property indirectDelegates using method get/isIndirectDelegates from org.ant
lr.tool.Grammar instance : java.lang.NullPointerException
     [java] java.util.Objects.requireNonNull(Objects.java:203)
     [java] java.util.ArrayList.removeAll(ArrayList.java:689)
     [java] org.antlr.tool.CompositeGrammar.getIndirectDelegates(CompositeGrammar.java:222)
     [java] org.antlr.tool.Grammar.getIndirectDelegates(Grammar.java:2620)
     [java] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] java.lang.reflect.Method.invoke(Method.java:497)
     [java] org.antlr.stringtemplate.language.ASTExpr.invokeMethod(ASTExpr.java:564)
     [java] org.antlr.stringtemplate.language.ASTExpr.rawGetObjectProperty(ASTExpr.java:515)
     [java] org.antlr.stringtemplate.language.ASTExpr.getObjectProperty(ASTExpr.java:417)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.attribute(ActionEvaluator.java:351)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.expr(ActionEvaluator.java:136)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.templateApplication(ActionEvaluator.java:216)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.expr(ActionEvaluator.java:126)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:84)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:149)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:705)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeTemplate(ASTExpr.java:750)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:680)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:660)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:149)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:705)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeTemplate(ASTExpr.java:750)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:680)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:660)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:149)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:705)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeTemplate(ASTExpr.java:750)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:680)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:660)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:149)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:705)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeTemplate(ASTExpr.java:750)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:680)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:660)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:149)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:705)
     [java] org.antlr.codegen.CodeGenerator.write(CodeGenerator.java:1281)
     [java] org.antlr.codegen.Target.genRecognizerFile(Target.java:94)
     [java] org.antlr.codegen.CodeGenerator.genRecognizer(CodeGenerator.java:466)
     [java] org.antlr.Tool.generateRecognizer(Tool.java:641)
     [java] org.antlr.Tool.process(Tool.java:454)
     [java] org.antlr.Tool.main(Tool.java:91)

BUILD FAILED
/root/.ccm/repository/2.0.5/build.xml:193: Java returned: 1

Total time: 20 seconds
Buildfile: /root/.ccm/repository/2.0.5/build.xml

init:

maven-ant-tasks-localrepo:

maven-ant-tasks-download:

maven-ant-tasks-init:

maven-declare-dependencies:

maven-ant-tasks-retrieve-build:

init-dependencies:
     [echo] Loading dependency paths from file: /root/.ccm/repository/2.0.5/build/build-dependencies.xml

check-gen-cli-grammar:

gen-cli-grammar:

check-gen-cql2-grammar:

gen-cql2-grammar:
     [echo] Building Grammar /root/.ccm/repository/2.0.5/src/java/org/apache/cassandra/cql/Cql.g  ...
     [java] error(10):  internal error: Can't get property indirectDelegates using method get/isIndirectDelegates from org.ant
lr.tool.Grammar instance : java.lang.NullPointerException
     [java] java.util.Objects.requireNonNull(Objects.java:203)
     [java] java.util.ArrayList.removeAll(ArrayList.java:689)
     [java] org.antlr.tool.CompositeGrammar.getIndirectDelegates(CompositeGrammar.java:222)
     [java] org.antlr.tool.Grammar.getIndirectDelegates(Grammar.java:2620)
     [java] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] java.lang.reflect.Method.invoke(Method.java:497)
     [java] org.antlr.stringtemplate.language.ASTExpr.invokeMethod(ASTExpr.java:564)
     [java] org.antlr.stringtemplate.language.ASTExpr.rawGetObjectProperty(ASTExpr.java:515)
     [java] org.antlr.stringtemplate.language.ASTExpr.getObjectProperty(ASTExpr.java:417)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.attribute(ActionEvaluator.java:351)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.expr(ActionEvaluator.java:136)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.templateApplication(ActionEvaluator.java:216)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.expr(ActionEvaluator.java:126)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:84)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:149)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:705)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeTemplate(ASTExpr.java:750)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:680)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:660)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:149)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:705)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeTemplate(ASTExpr.java:750)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:680)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:660)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:149)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:705)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeTemplate(ASTExpr.java:750)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:680)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:660)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:149)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:705)
     [java] org.antlr.codegen.CodeGenerator.write(CodeGenerator.java:1281)
     [java] org.antlr.codegen.Target.genRecognizerFile(Target.java:94)
     [java] org.antlr.codegen.CodeGenerator.genRecognizer(CodeGenerator.java:466)
     [java] org.antlr.Tool.generateRecognizer(Tool.java:641)
     [java] org.antlr.Tool.process(Tool.java:454)
     [java] org.antlr.Tool.main(Tool.java:91)

BUILD FAILED
/root/.ccm/repository/2.0.5/build.xml:219: Java returned: 1

Total time: 4 seconds
Buildfile: /root/.ccm/repository/2.0.5/build.xml

init:

maven-ant-tasks-localrepo:

maven-ant-tasks-download:

maven-ant-tasks-init:

maven-declare-dependencies:

maven-ant-tasks-retrieve-build:

init-dependencies:
     [echo] Loading dependency paths from file: /root/.ccm/repository/2.0.5/build/build-dependencies.xml

check-gen-cli-grammar:

gen-cli-grammar:

check-gen-cql2-grammar:

gen-cql2-grammar:

check-gen-cql3-grammar:

gen-cql3-grammar:
     [echo] Building Grammar /root/.ccm/repository/2.0.5/src/java/org/apache/cassandra/cql3/Cql.g  ...
     [java] error(10):  internal error: Can't get property indirectDelegates using method get/isIndirectDelegates from org.ant
lr.tool.Grammar instance : java.lang.NullPointerException
     [java] java.util.Objects.requireNonNull(Objects.java:203)
     [java] java.util.ArrayList.removeAll(ArrayList.java:689)
     [java] org.antlr.tool.CompositeGrammar.getIndirectDelegates(CompositeGrammar.java:222)
     [java] org.antlr.tool.Grammar.getIndirectDelegates(Grammar.java:2620)
     [java] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] java.lang.reflect.Method.invoke(Method.java:497)
     [java] org.antlr.stringtemplate.language.ASTExpr.invokeMethod(ASTExpr.java:564)
     [java] org.antlr.stringtemplate.language.ASTExpr.rawGetObjectProperty(ASTExpr.java:515)
     [java] org.antlr.stringtemplate.language.ASTExpr.getObjectProperty(ASTExpr.java:417)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.attribute(ActionEvaluator.java:351)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.expr(ActionEvaluator.java:136)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.templateApplication(ActionEvaluator.java:216)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.expr(ActionEvaluator.java:126)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:84)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:149)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:705)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeTemplate(ASTExpr.java:750)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:680)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:660)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:149)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:705)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeTemplate(ASTExpr.java:750)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:680)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:660)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:149)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:705)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeTemplate(ASTExpr.java:750)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:680)
     [java] org.antlr.stringtemplate.language.ASTExpr.writeAttribute(ASTExpr.java:660)
     [java] org.antlr.stringtemplate.language.ActionEvaluator.action(ActionEvaluator.java:86)
     [java] org.antlr.stringtemplate.language.ASTExpr.write(ASTExpr.java:149)
     [java] org.antlr.stringtemplate.StringTemplate.write(StringTemplate.java:705)
     [java] org.antlr.codegen.CodeGenerator.write(CodeGenerator.java:1281)
     [java] org.antlr.codegen.Target.genRecognizerFile(Target.java:94)
     [java] org.antlr.codegen.CodeGenerator.genRecognizer(CodeGenerator.java:466)
     [java] org.antlr.Tool.generateRecognizer(Tool.java:641)
     [java] org.antlr.Tool.process(Tool.java:454)
     [java] org.antlr.Tool.main(Tool.java:91)

BUILD FAILED
/root/.ccm/repository/2.0.5/build.xml:230: Java returned: 1

Total time: 5 seconds
--- Cassandra Build -------------------
`ant jar` failed. Retry #1...
`ant jar` failed. Retry #2...
------------------------------------------------------
I am new to Cassandra. Would like to get help from you. Thanks and appreciated.

**Comment by ptnapoleon** [comment]
Unfortunately, Cassandra versions in the 2.0.X series cannot be compiled with JDK8. This is unrelated to ccm. You must either install and use JDK7 instead, or only use Cassandra 2.1.
