### ISSUE TITLE
Stress command with 2.1.4 returns 'No command specified'

### ISSUE THREAD

**Issue by analytically** [pcmanus/ccm#319]
>`ccm stress`

`No command specified`

**Comment by ptnapoleon** [comment]
Cassandra stress in 2.1 underwent a large refactor from the stress that ships with 2.0. There is no longer a default command when just `cassandra-stress` is run. This error message is being returned from stress, not ccm, and is valid. For usage, try running `tools/bin/cassandra-stress help` from inside a checkout of the Cassandra repository. CCM stores the ones it uses in `~/.ccm/repository`.
