### ISSUE TITLE
Support clusters running mixed Cassandra versions

### ISSUE THREAD

**Issue by spodkowinski** [pcmanus/ccm#341]
It would be great to be able to use ccm to test upgrade scenarios by upgrading individual nodes one by one. This would involve stopping a single node using ccm, changing the install dir while keeping the data dir, and starting the node again. This would also be useful for writing dtest cases for updates, as there will be more frequent Cassandra releases in the future.

**Comment by spodkowinski** [comment]
Looks like this seems to be already possible from the api, see *upgrade* tests in cassandra-dtest.

**Comment by ptnapoleon** [comment]
It is technically also possible from the command line, albeit clunky and unpleasant.

**Comment by spodkowinski** [comment]
I've just modified the setversion command to make this more convenient. Will do a PR after I'm done.
https://github.com/pcmanus/ccm/compare/master...spodkowinski:feat/setnodeversion?expand=1
