### ISSUE TITLE
Not supporting windows 64 bit

### ISSUE THREAD

**Issue by pavankumarp89** [pcmanus/ccm#355]

**Comment by ptnapoleon** [comment]
Could you clarify this issue? Windows 7-10, 32 or 64 bit are supported. As well as the corresponding Windows Server versions.

**Comment by pavankumarp89** [comment]
I have downloaded ccm 2.0.4.1 on windows 10 64 bit configured java,python and ant in class path
and ran below commands
python setup.py install
pip install ccm
Both are successful.

When I run ccm command getting below error
G:\Engineering Softwares\Cassandra\ccm-2.0.4.1>ccm create test -v 2.1.2
'ccm' is not recognized as an internal or external command,
operable program or batch file.

When I tried to run from python shell
G:\Engineering Softwares\Cassandra\ccm-2.0.4.1>python ccm
ERROR!  64-bit os and 32-bit python distribution found.  ccm requires matching architectures.

**Comment by pavankumarp89** [comment]
I got the issue its because of pyton was 32 bit version,
However when running the ccm start getting below error message
ccm create --version 2.2.0 --nodes 3 --start test_cluster
Current cluster is now: test_cluster
Setting up Cassandra environment
*---------------------------------------------------------------------*
*---------------------------------------------------------------------*

    WARNING!  Automatic page file configuration detected.
    It is recommended that you disable swap when running Cassandra
    for performance and stability reasons.

**Comment by mambocab** [comment]
It sounds like you got ccm working -- glad to hear that. The warning about disabling swap is unrelated to ccm, however. That's just part of configuring your system so Cassandra performs well. Cassandra will still perform correctly with swap enabled, but you will run into performance issues if the node runs out of memory.

I don't know how to disable swap on Windows. If you're just getting started with Cassandra, check out the Cassandra users channel on IRC: http://irc.lc/freenode/cassandra/
