### ISSUE TITLE
CMM Error When Running "ccm create"

### ISSUE THREAD

**Issue by prebola** [pcmanus/ccm#378]
I get this error when trying to do “ccm create –v 2.1.9 –n 1 mycluster” on my Windows laptop:
 
BUILD FAILED
C:\Users\prebolab\.ccm\repository\2.1.9\build.xml:348: artifact:pom doesn't support the "groupId" attribute
 
I believe I have the latest version of ant which is mentioned here:
 
http://wiki.apache.org/cassandra/RunningCassandraInEclipse#artifact:pom_error
 
Would anyone have any recommendations?

Thank you.

Brian

**Comment by ptnapoleon** [comment]
What version of the JDK are you using?

**Comment by prebola** [comment]
jdk1.8.0_40

**Comment by ptnapoleon** [comment]
So your ant is version 1.9.4 or greater, then?

**Comment by ptnapoleon** [comment]
Also, you are using the newest source code of CCM, yes?

**Comment by ptnapoleon** [comment]
I can confirm that jdk1.8.0_51 with ant 1.9.4 on Windows 10 with the newest CCM does compile, so this is going to end up being some sort of environmental issue.

**Comment by prebola** [comment]
Apache Ant(TM) version 1.9.6 compiled on June 29 2015

I installed CCM from ccm-2.0.2.tar.gz.

**Comment by prebola** [comment]
Using Windows 7 Enterprise SP1.

**Comment by ptnapoleon** [comment]
Okay, well the newest ccm version was 2.0.4.1, and I just released 2.0.5 seconds ago. Can you try 2.0.5? You can either get it from pypi, or by installing from source (this repository).

**Comment by prebola** [comment]
I downloaded 2.0.5 from https://pypi.python.org/pypi/ccm/2.0.5, however, I get the same error.  I attached the full log file.

**Comment by prebola** [comment]
Buildfile: C:\Users\prebolab\.ccm\repository\2.1.9\build.xml

init:
    [mkdir] Created dir: C:\Users\prebolab\.ccm\repository\2.1.9\build\classes\main
    [mkdir] Created dir: C:\Users\prebolab\.ccm\repository\2.1.9\build\classes\thrift
    [mkdir] Created dir: C:\Users\prebolab\.ccm\repository\2.1.9\build\test\lib
    [mkdir] Created dir: C:\Users\prebolab\.ccm\repository\2.1.9\build\test\classes
    [mkdir] Created dir: C:\Users\prebolab\.ccm\repository\2.1.9\src\gen-java
    [mkdir] Created dir: C:\Users\prebolab\.ccm\repository\2.1.9\build\lib

maven-ant-tasks-localrepo:

maven-ant-tasks-download:
     [echo] Downloading Maven ANT Tasks...
      [get] Getting: http://repo2.maven.org/maven2/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar
      [get] To: C:\Users\prebolab\.ccm\repository\2.1.9\build\maven-ant-tasks-2.1.3.jar

maven-ant-tasks-init:

maven-declare-dependencies:

BUILD FAILED
C:\Users\prebolab\.ccm\repository\2.1.9\build.xml:348: artifact:pom doesn't support the "groupId" attribute

Total time: 4 seconds
Buildfile: C:\Users\prebolab\.ccm\repository\2.1.9\build.xml

init:

maven-ant-tasks-localrepo:

maven-ant-tasks-download:

maven-ant-tasks-init:

maven-declare-dependencies:

BUILD FAILED
C:\Users\prebolab\.ccm\repository\2.1.9\build.xml:348: artifact:pom doesn't support the "groupId" attribute

Total time: 0 seconds
Buildfile: C:\Users\prebolab\.ccm\repository\2.1.9\build.xml

init:

maven-ant-tasks-localrepo:

maven-ant-tasks-download:

maven-ant-tasks-init:

maven-declare-dependencies:

BUILD FAILED
C:\Users\prebolab\.ccm\repository\2.1.9\build.xml:348: artifact:pom doesn't support the "groupId" attribute

Total time: 0 seconds
--- Cassandra Build -------------------


`ant jar` failed. Retry #1...



`ant jar` failed. Retry #2...

**Comment by ptnapoleon** [comment]
Well now the important thing to check is to see if this is CCM's fault. Can you download the C* source yourself via git, and see if you can compile 2.1.9 separately?

```
git clone https://github.com/apache/cassandra
cd cassandra
git checkout cassandra-2.1.9
ant
```

**Comment by prebola** [comment]
Thanks for the help by the way.  It does look like 2.1.9 has the error when I compile it.

C:\cassandra\cassandra>ant
Buildfile: C:\cassandra\cassandra\build.xml

init:
    [mkdir] Created dir: C:\cassandra\cassandra\build\classes\main
    [mkdir] Created dir: C:\cassandra\cassandra\build\classes\thrift
    [mkdir] Created dir: C:\cassandra\cassandra\build\test\lib
    [mkdir] Created dir: C:\cassandra\cassandra\build\test\classes
    [mkdir] Created dir: C:\cassandra\cassandra\src\gen-java
    [mkdir] Created dir: C:\cassandra\cassandra\build\lib

maven-ant-tasks-localrepo:

maven-ant-tasks-download:
     [echo] Downloading Maven ANT Tasks...
      [get] Getting: http://repo2.maven.org/maven2/org/apache/maven/maven-ant-ta
sks/2.1.3/maven-ant-tasks-2.1.3.jar
      [get] To: C:\cassandra\cassandra\build\maven-ant-tasks-2.1.3.jar

maven-ant-tasks-init:

maven-declare-dependencies:

BUILD FAILED
C:\cassandra\cassandra\build.xml:348: artifact:pom doesn't support the "groupId"
 attribute

Total time: 0 seconds

C:\cassandra\cassandra>

**Comment by ptnapoleon** [comment]
Well this is at least somewhat good news. I recommend you go to the #cassandra irc channel on freenode, or email the user mailing list with your problem. They should be able to help.

**Comment by prebola** [comment]
Ok - thank you.
