### ISSUE TITLE
ccm fails to start cqlsh for cassandra version 2.2.2 and newer

### ISSUE THREAD

**Issue by lhog** [pcmanus/ccm#382]
>[ak@arch-workold ~]$ ccm remove X
>[ak@arch-workold ~]$ ccm create X -n 5 -v 2.1.9 -s
>Current cluster is now: X
>[ak@arch-workold ~]$ ccm node1 cqlsh
>Connected to X at 127.0.0.1:9042.
>[cqlsh 5.0.1 | Cassandra 2.1.9-SNAPSHOT | CQL spec 3.2.0 | Native protocol v3]
>Use HELP for help.
>cqlsh> 

^^^^^^^SUCCESS^^^^^^^

>[ak@arch-workold ~]$ ccm remove X
>[ak@arch-workold ~]$ ccm create X -n 5 -v 2.2.2 -s
>Current cluster is now: X
>[ak@arch-workold ~]$ ccm node1 cqlsh
>  File "/home/ak/.ccm/repository/2.2.2/bin/cqlsh.py", line 103
>    except ImportError, e:
>                      ^
>SyntaxError: invalid syntax

^^^^^^^  FAIL ^^^^^^^

Python 2.7.10
ccm version 2.0.5

**Comment by ptnapoleon** [comment]
That error message comes from using Python 3 with cqlsh. Are you sure you're using Python 2.7.10? I can confirm 2.2.2's C* works fine with that python version. Additionally, this is an issue you're having with C*, nothing to do with ccm. Please ask on the C* user mail list for help.

**Comment by mambocab** [comment]
@ptnapoleon looks like your comment got markdown'd. He means

> Additionally, this is an issue you're having with C\*, nothing to do with ccm. Please ask on the C\* user mail list for help.

C\* being Cassandra.

**Comment by ptnapoleon** [comment]
Thanks Jim

**Comment by lhog** [comment]
All right figured that out. For the future readers, founded that via Google.
C* >= 2.2.2 will require the following change, if you see the error message from original post
file $HOME/.ccm/repository/2.2.2/bin/cqlsh
line
```python "`dirname "$0"`/cqlsh.py" "$@"```
to
```python2 "`dirname "$0"`/cqlsh.py" "$@"```
