### ISSUE TITLE
cannot sart ccm on Ubuntu 12.04

### ISSUE THREAD

**Issue by kunaljha5** [pcmanus/ccm#383]
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ ccm create test -v 2.1.5
Current cluster is now: test
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ ccm list
  demo_1node
 *test
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ ccm populate -n 3
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ ccm list
  demo_1node
 *test
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ ccm status
Cluster: 'test'
---------------
node1: DOWN (Not initialized)
node3: DOWN (Not initialized)
node2: DOWN (Not initialized)
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ ccm status
Cluster: 'test'
---------------
node1: DOWN (Not initialized)
node3: DOWN (Not initialized)
node2: DOWN (Not initialized)
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ ccm start
Traceback (most recent call last):
  File "/usr/local/bin/ccm", line 72, in <module>
    cmd.run()
  File "/usr/local/lib/python2.7/dist-packages/ccmlib/cmds/cluster_cmds.py", line 544, in run
    profile_options=profile_options) is None:
  File "/usr/local/lib/python2.7/dist-packages/ccmlib/cluster.py", line 277, in start
    p = node.start(update_pid=False, jvm_args=jvm_args, profile_options=profile_options)
  File "/usr/local/lib/python2.7/dist-packages/ccmlib/node.py", line 479, in start
    common.check_socket_available(itf)
  File "/usr/local/lib/python2.7/dist-packages/ccmlib/common.py", line 410, in check_socket_available
    raise UnavailableSocketError("Inet address %s:%s is not available: %s" % (addr, port, msg))
ccmlib.common.UnavailableSocketError: Inet address 127.0.0.1:9042 is not available: [Errno 98] Address already in use
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ ps ax | grep CassandraDaemon
 6706 pts/2    Sl     0:30 java -ea -javaagent:./../lib/jamm-0.3.0.jar -XX:+CMSClassUnloadingEnabled -XX:+UseThreadPriorities -XX:ThreadPriorityPolicy=42 -Xms1966M -Xmx1966M -Xmn400M -XX:+HeapDumpOnOutOfMemoryError -Xss256k -XX:StringTableSize=1000003 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=1 -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+UseTLAB -XX:+PerfDisableSharedMem -XX:CompileCommandFile=./../conf/hotspot_compiler -XX:CMSWaitDuration=10000 -XX:+CMSParallelInitialMarkEnabled -XX:+CMSEdenChunksRecordAlways -XX:CMSWaitDuration=10000 -XX:+UseCondCardMark -Djava.net.preferIPv4Stack=true -Dcassandra.jmx.local.port=7199 -XX:+DisableExplicitGC -Djava.library.path=./../lib/sigar-bin -Dlogback.configurationFile=logback.xml -Dcassandra.logdir=./../logs -Dcassandra.storagedir=./../data -cp ./../conf:./../build/classes/main:./../build/classes/thrift:./../lib/ST4-4.0.8.jar:./../lib/airline-0.6.jar:./../lib/antlr-runtime-3.5.2.jar:./../lib/apache-cassandra-2.2.1.jar:./../lib/apache-cassandra-clientutil-2.2.1.jar:./../lib/apache-cassandra-thrift-2.2.1.jar:./../lib/cassandra-driver-core-2.2.0-rc2-SNAPSHOT-20150617-shaded.jar:./../lib/commons-cli-1.1.jar:./../lib/commons-codec-1.2.jar:./../lib/commons-lang3-3.1.jar:./../lib/commons-math3-3.2.jar:./../lib/compress-lzf-0.8.4.jar:./../lib/concurrentlinkedhashmap-lru-1.4.jar:./../lib/crc32ex-0.1.1.jar:./../lib/disruptor-3.0.1.jar:./../lib/ecj-4.4.2.jar:./../lib/guava-16.0.jar:./../lib/high-scale-lib-1.0.6.jar:./../lib/jackson-core-asl-1.9.2.jar:./../lib/jackson-mapper-asl-1.9.2.jar:./../lib/jamm-0.3.0.jar:./../lib/javax.inject.jar:./../lib/jbcrypt-0.3m.jar:./../lib/jcl-over-slf4j-1.7.7.jar:./../lib/jna-4.0.0.jar:./../lib/joda-time-2.4.jar:./../lib/json-simple-1.1.jar:./../lib/libthrift-0.9.2.jar:./../lib/log4j-over-slf4j-1.7.7.jar:./../lib/logback-classic-1.1.3.jar:./../lib/logback-core-1.1.3.jar:./../lib/lz4-1.3.0.jar:./../lib/metrics-core-3.1.0.jar:./../lib/metrics-logback-3.1.0.jar:./../lib/netty-all-4.0.23.Final.jar:./../lib/ohc-core-0.3.4.jar:./../lib/ohc-core-j8-0.3.4.jar:./../lib/reporter-config-base-3.0.0.jar:./../lib/reporter-config3-3.0.0.jar:./../lib/sigar-1.6.4.jar:./../lib/slf4j-api-1.7.7.jar:./../lib/snakeyaml-1.11.jar:./../lib/snappy-java-1.1.1.7.jar:./../lib/stream-2.5.2.jar:./../lib/super-csv-2.1.0.jar:./../lib/thrift-server-0.3.7.jar:./../lib/jsr223/*/*.jar org.apache.cassandra.service.CassandraDaemon
11030 pts/2    S+     0:00 grep --color=auto CassandraDaemon
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$
kill -9 6706
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ 
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ 
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ 
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ 
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ 
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ ps ax | grep CassandraDaemon
11075 pts/2    S+     0:00 grep --color=auto CassandraDaemon
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ ifconfig lo
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:43126 errors:0 dropped:0 overruns:0 frame:0
          TX packets:43126 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2808319 (2.8 MB)  TX bytes:2808319 (2.8 MB)

ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ ifconfig lo:
lo:       Link encap:Local Loopback  
          UP LOOPBACK RUNNING  MTU:16436  Metric:1

ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ ifconfig lo:0
lo:0      Link encap:Local Loopback  
          inet addr:127.0.0.2  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:16436  Metric:1

ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ ifconfig lo:1
lo:1      Link encap:Local Loopback  
          inet addr:127.0.0.3  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:16436  Metric:1

ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ ifconfig lo:2
lo:2      Link encap:Local Loopback  
          inet addr:127.0.0.4  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:16436  Metric:1

ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ 
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ 
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin/ccm$ ccm start 
[node1 ERROR] Error: Could not find or load main class org.apache.cassandra.service.CassandraDaemon

**Comment by mambocab** [comment]
You dealt with the first error -- that there was already an instance of Cassandra running -- correctly.

However, I'm not sure why the `Error: Could not find or load main class org.apache.cassandra.service.CassandraDaemon` error is happening. Have you tried starting over, first using `ccm remove` to get rid of your old cluster? Another thing you might try is deleting `~/.ccm/repository/`. This will delete all the cached downloads and builds. Finally, you can delete the `~/.ccm/' directory -- this will delete all your clusters, but give you a clean slate to work from with ccm.

**Comment by ptnapoleon** [comment]
Using the command `ccm invalidatecache` will delete that folder.

**Comment by kunaljha5** [comment]
issue closed 
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin$ ccm remove
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin$ ccm invalidatecache
[Errno 2] No such file or directory: '/home/ejhakun/.ccm/repository'
Error while deleting cache. Please attempt manually.
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin$ ccm list
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin$ ccm status
No currently active cluster (use ccm cluster switch)
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin$ 

ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin$ kill -9 474
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin$ ps ax | grep CassandraDaemon
 1538 pts/8    S+     0:00 grep --color=auto CassandraDaemon
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin$ 
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin$ 
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin$ ccm create test -v 2.2.1
Downloading http://archive.apache.org/dist/cassandra/2.2.1/apache-cassandra-2.2.1-src.tar.gz to /tmp/ccm-caWMZb.tar.gz (22.898MB)
  24010728  [100.00%]
Extracting /tmp/ccm-caWMZb.tar.gz as version 2.2.1 ...
Compiling Cassandra 2.2.1 ...


Current cluster is now: test
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin$ 
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin$ 
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin$ ccm list
 *test
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin$ ccm populate -n 2
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin$ ccm status
Cluster: 'test'
---------------
node1: DOWN (Not initialized)
node2: DOWN (Not initialized)
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin$ ccm start
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin$ ccm status
Cluster: 'test'
---------------
node1: UP
node2: UP
ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin$ ifconfig 
eth0      Link encap:Ethernet  HWaddr d4:be:d9:01:33:48  
          inet addr:147.128.217.102  Bcast:147.128.217.255  Mask:255.255.254.0
          inet6 addr: fe80::d6be:d9ff:fe01:3348/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:892202 errors:0 dropped:0 overruns:0 frame:0
          TX packets:218602 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:262282264 (262.2 MB)  TX bytes:32929220 (32.9 MB)
          Interrupt:20 Memory:e6e00000-e6e20000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:62125 errors:0 dropped:0 overruns:0 frame:0
          TX packets:62125 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:8063820 (8.0 MB)  TX bytes:8063820 (8.0 MB)

ejhakun@5CPS8R1:~/Downloads/cassandra/apache-cassandra-2.2.1/bin$ 


Finally i can move ahed thanks to you both :+1:
