### ISSUE TITLE
Determine desired set_log_level behavior 

### ISSUE THREAD

**Issue by jkni** [pcmanus/ccm#387]
We recently introduced changes to C* that separate logging into a system.log that is filtered to INFO and above by default, as well as a debug.log that is filtered to DEBUG and above by default.

Before, set_log_level set the log level of a core root appender to the desired level. This would impact both C* and any other libraries and redirect this to system.log.

Now, set_log_level does not have a clearly defined behavior. I recently PRed a patch that sets the log level of this root appender and a newly added C* appender, but if set_log_level is called with a value higher than DEBUG (such as INFO), debug.log will only contain INFO entries (and not DEBUG) since the appender is set to INFO. This seems to defeat the point of a debug.log.

I propose the following changes, where we have an ascending scale of logging from ['trace', 'debug', 'info', 'warn', 'error'].

If set_log_level is called with 'trace', we set both appenders to 'trace'. Then, debug.log will contain all entries and system.log will contain only INFO and up.

If set_log_level is called with 'debug', we set both appenders to 'debug'. Then, debug.log will contain all entries debug and up and system.log will contain only INFO and up.

If set_log_level is called with 'info', this is a noop. Debug.log will contain C* entries debug and up and other libraries INFO and up, while system.log will contain INFO and up.

If set_log_level is called with 'warn', we set the system.log filter to WARN.

If set_log_level is called with 'error', we set the system.log filter to ERROR.

This is a decidedly more complicated behavior, but it seems to best fit the intention of the separate system.log and debug.log. Thoughts?

EDIT: I should note that I'm willing to implement this - I'd just like desired behavior to be decided upon first.

**Comment by ptnapoleon** [comment]
I like the proposed behavior. I don't think any other users of ccm will be strongly affected by our changes, so we should mostly consider what is useful for testing. @mambocab, thoughts?

**Comment by jkni** [comment]
Relevant PR merged.
