### ISSUE TITLE
C* 3.0 doesn't clean up properly upon shutdown

### ISSUE THREAD

**Issue by kishkaru** [pcmanus/ccm#391]
Shutting down a 3.0 cluster on Windows (currently tested with 3.0.0-rc1) via `ccm stop` most of the time closes the Java processes, but doesn't remove the `cassandra.pid` files in the node directories. This causes subsequent starts of the cluster to fail with `Exception: Timed out waiting for pid file`. Sometimes only a few pid files are removed, leaving at least one, which still causes a failed launch. Other times the Java processes are left alive as well.

In most cases, killing all alive Java processes and removing each pid file in the node directories fixes the issue. However, even if there are no old pids lying around, sometimes it still fails to start (with the above timeout error). Retrying usually works in this case. Regression introduced in C* 3.0, as this was not an issue with C* 2.2.

**Comment by ptnapoleon** [comment]
So I don't believe `ccm stop` should remove the cassandra.pid files. `ccm start` removes the old pid right before trying to start the new process. Check out line `530` in node.py

**Comment by ptnapoleon** [comment]
Found the issue. Environmental. Leaving this open, as we need a flag that when set, provides better debug output of windows start failures. Essentially we just need to make it perform the equivalent of this patch:

```
diff --git a/ccmlib/node.py b/ccmlib/node.py
index cd5ade1..3b4e068 100644
--- a/ccmlib/node.py
+++ b/ccmlib/node.py
@@ -535,11 +535,15 @@ class Node(object):
             # clean up any old dirty_pid files from prior runs
             if (os.path.isfile(self.get_path() + "/dirty_pid.tmp")):
                 os.remove(self.get_path() + "/dirty_pid.tmp")
-            process = subprocess.Popen(args, cwd=self.get_bin_dir(), env=env, stdout=FNULL, stderr=subprocess.PIPE)
+            process = subprocess.Popen(args, cwd=self.get_bin_dir(), env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
         else:
             process = subprocess.Popen(args, env=env, stdout=FNULL, stderr=subprocess.PIPE)
         # Our modified batch file writes a dirty output with more than just the pid - clean it to get in parity
         # with *nix operation here.
+
+        stdout, stderr = process.communicate()
+        print stdout
+        print stderr
         if common.is_win():
             self.__clean_win_pid()
             self._update_pid(process)
```

**Comment by kishkaru** [comment]
Issue related to using the wrong JDK (jdk7) while attempting to start C* 3.0. Using JDK8 fixed the issue.
