### ISSUE TITLE
Integrating CCM into UT environment causing table create timeouts

### ISSUE THREAD

**Issue by angelcaban** [pcmanus/ccm#400]
Opening an issue because we're looking to get some insight on some issues that we are seeing. Our steps are as follows:

1. For our unit testing environment, we set up a 3-node Cassandra cluster before running any tests.
(ccm create [generated_name] -n 3 && ccm start)

2. Individual unit tests create new keyspaces and tables and later abandon them (no table or keyspace drops performed)

3. After a few tests, we eventually hit a timeout error in one of our UT's due to a table create that takes around 12 seconds to complete. (The status logging from Cassandra shows 7 active and 9 pending stages for migration, memtable & compaction)

Before attempting to increase the timeouts, I was wondering if this kind of behavior makes any sense? 

Many Thanks!

**Comment by ptnapoleon** [comment]
How many tests are running, and how many keyspaces/tables are they creating each? And it's the same CCM cluster each time? The issue could just be you're making too many tables at once, which is an inherent C* limitation.

**Comment by angelcaban** [comment]
Thank you for the response.

We're creating one table per test and there are at least a dozen tests running one after another doing similar operations on the cass (creating unique ks and tables, filling in data, running operations)

I did try doing a ccm remove followed by a create command between tests and that seems to do the business for the added cost of tear-down and setup time between tests.

I'm guessing this is correct way to go about it?

**Comment by ptnapoleon** [comment]
A dozen keyspace/table pairs should pose absolutely no problem. I was concerned you were in the low hundreds. Destroying/recreating the cluster would solve the issue, but yes, there is added time. Perhaps you could just try
```
ccm clear
ccm start
```
This is functionally similar, but may be slightly faster, as you aren't removing everything.

**Comment by angelcaban** [comment]
Sorry for keeping the issue opened for so long.

Clearing and restarting definitely seems the way to go.

Thanks for the response!
