### ISSUE TITLE
Compatibility with jenv

### ISSUE THREAD

**Issue by neverfox** [pcmanus/ccm#414]
I use jenv to manage my Java installations and I get the following error when starting a cluster (though it seems to be harmless):

```
objc[10064]: Class JavaLaunchHelper is implemented in both /usr/local/opt/jenv/versions/oracle64-1.8.0.66/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
```

**Comment by ptnapoleon** [comment]
This is just a known JVM issue on OSX. You should see this when using JDK7 or JDK8, with or without jenv. It is entirely harmless, though annoying. It's entirely a problem with C* and the JVM, nothing CCM can do about it.
