### ISSUE TITLE
TypeError exception: node.py:1284 in __update_yaml

### ISSUE THREAD

**Issue by angelcaban** [pcmanus/ccm#434]
Hi

I'm getting an error recently while calling set_configuration_options, although I could've sworn this was working. This may be something dumb on my part, but just in case there's a bug I wanted to file an issue.

    Traceback (most recent call last):
      File "cass_ut_init.py", line 116, in <module>
        main(sys.argv[1:])
      File "cass_ut_init.py", line 91, in main
        node.set_configuration_options(node_options)
      File "node.py", line 249, in set_configuration_options
        self.import_config_files()
      File "node.py", line 1124, in import_config_files
        self.__update_yaml()
      File "node.py", line 1284, in __update_yaml
        data[name][option] = full_options[name][option]

My code:
```python
    node = cluster.create_node(name              = nodeInfo[0],
                                       thrift_interface  = nodeInfo[1],
                                       storage_interface = nodeInfo[2],
                                       binary_interface  = nodeInfo[3],
                                       jmx_port          = nodeInfo[4],
                                       initial_token     = nodeInfo[5],
                                       remote_debug_port = str(0),
                                       auto_bootstrap    = False,
                                       save              = False)
    node_options = {
            'auto_snapshot':             False,
            'inter_dc_tcp_nodelay':      True,
            'server_encryption_options': 'none'
    };
    node.set_configuration_options(node_options)
```

Does anything stand out?

Thanks

**Comment by ptnapoleon** [comment]
Looks like it wasn't broken by anything recent, afaict. I see the bug though, shouldn't be hard to fix.

**Comment by ptnapoleon** [comment]
Okay, I've fixed the TypeError, but I should note, I don't think 'none' is a valid option for `server_encryption_options`, at least based on my reading of the 2.1 yaml

**Comment by angelcaban** [comment]
You're right about server_encryption_options. I read the datastax doc wrong. Looks like a nested dictionary.

But, thank you for looking into it.
