### ISSUE TITLE
ccm install fails on Mac OS X El Capitan: "Permission denied: '/usr/local/bin/ccm'"

### ISSUE THREAD

**Issue by anievagomez** [pcmanus/ccm#439]
Environment: OS X El Capitan v10.11.12; Cassandra v3.0.0; Python 2.7.10

Install fails using "$ ./setup.py install" since it tries to write to /usr/local/bin, a location that is protected in "El Capitan" by the "System Integrity Protection (SIP)" feature. One can not gain access to this directory even if one becomes root. 
It is not feasible to disable SIP in my current environment. Is there a way to configure the setup process to use a different install directory?

**Comment by ptnapoleon** [comment]
It is my understanding that SIP restricts access to /usr, *except* /usr/local/. I have SIP on with El Capitan and don't have issues. That said, you can most likely install with the --user flag, `./setup.py install --user`, which should place it elsewhere.

**Comment by anievagomez** [comment]
Hi Phillip,
Your recommendation worked and I resolved my problem.
Thank you for your prompt response.
Augusto Nieva
