### ISSUE TITLE
renew fixture SSL certificates

### ISSUE THREAD

**Issue by thibaultCha** [pcmanus/ccm#446]
It seems the certificate expired a while ago and thus, prevent clients from using them to verify their connection.

keystore.jks/truststore.jks
```
Your keystore contains 1 entry

Alias name: cassandra
Creation date: Oct 3, 2014
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: CN=Philip Thompson, OU=TE, O=DataStax, L=Santa Clara, ST=CA, C=TE
Issuer: CN=Philip Thompson, OU=TE, O=DataStax, L=Santa Clara, ST=CA, C=TE
Serial number: 3ff374e8
Valid from: Fri Oct 03 08:46:47 PDT 2014 until: Thu Jan 01 07:46:47 PST 2015
```

Would you mind a PR updating them (potentially with certificates valid for a longer period of time)? Or do you plan on updating them?

**Comment by thibaultCha** [comment]
Also giving out the certificate in PEM format would be a very nice feature:

Again taking the example of doing testing on top of a ccm cluster when the C* client needs a PEM format certificate.

**Comment by ptnapoleon** [comment]
I would love a PR updating them, with the longer validity time. Thanks.
