### ISSUE TITLE
Unable to start ccm after upgrade "Error Loading /home/ltpeck/.ccm/test/node1/node.conf, missing property: 'byteman_port'"

### ISSUE THREAD

**Issue by LtTempletonPeck** [pcmanus/ccm#454]
Upgraded to latest `pip install ccm --upgrade`

Can no longer start existing ccm clusters `Error Loading /home/ltpeck/.ccm/test/node1/node.conf, missing property: 'byteman_port'`

**Comment by ptnapoleon** [comment]
CCM clusters are entirely for development, and never intended to be long lived. We do not attempt to support clusters from previous ccm versions, so upgrading ccm while you have live clusters will break them.

I will add a note to the README explicitly spelling this out. For your specific case, adding `byteman_port: '0'` to your node.conf files, may resolve the issue, but it is possible that other changes need to be made. Rolling back your ccm version may be the best/only fix.

**Comment by LtTempletonPeck** [comment]
Seems fair. A warning in the README might avoid confusion.
