### ISSUE TITLE
ccm on windows 10 - python error

### ISSUE THREAD

**Issue by dins2k2** [pcmanus/ccm#467]
Hi,

I installed ccm perfectly on windows 10 using below pacakges

python-3.4.4.amd64.msi, PyYAML-3.11.win-amd64-py3.4.exe, six-1.10.0-py2.py3-none-any.whl, psutil-4.1.0.win-amd64-py3.4.exe, jdk-8u73-windows-x64.exe, apache-ant-1.9.6-bin
ccm-master zip file from GitHub.

I tried to create a cluster named cluster1, getting below error. 

$ ccm create cluster1 -v 2.1.5
Current cluster is now: cluster1
$ ccm populate -n 3
$ ccm status
Cluster: 'cluster1'

node2: DOWN (Not initialized)
node1: DOWN (Not initialized)
node3: DOWN (Not initialized)

**$ ccm start
Traceback (most recent call last):
  File "E:\Studies\Cassandra\ccm\ccm-master\ccm.py", line 74, in <module>
    cmd.run()
  File "E:\Studies\Cassandra\ccm\ccm-master\ccmlib\cmds\cluster_cmds.py", line 583, in run
    allow_root=self.options.allow_root) is None:
  File "E:\Studies\Cassandra\ccm\ccm-master\ccmlib\cluster.py", line 335, in start
    p = node.start(update_pid=False, jvm_args=jvm_args, profile_options=profile_options, verbose=verbose, quiet_start=quiet_start, allow_root=allow_root)
  File "E:\Studies\Cassandra\ccm\ccm-master\ccmlib\node.py", line 499, in start
    if common.is_win() and not common.is_ps_unrestricted() and self.cluster.version() >= '2.1':
  File "E:\Studies\Cassandra\ccm\ccm-master\ccmlib\common.py", line 270, in is_ps_unrestricted
    if "Unrestricted" in p.communicate()[0]:
TypeError: 'str' does not support the buffer interface**

I have a question. Do I need to create alias loopback IPs(127.0.0.2, 127.0.0.3, 127.0.0.3, etc..) as same like Mac OS in Windows as well?
Even I tried for C* version 3.0.3, getting the same error.

**Note : I have set the Powershell ExecutuionPolicy as Unrestricted.**

Please help me to fix this.

Thanks,
Dinesh

**Comment by mambocab** [comment]
@ptnapoleon a quick Google makes this look like a Py3 encoding error: http://stackoverflow.com/questions/5471158/typeerror-str-does-not-support-the-buffer-interface

**Comment by kishkaru** [comment]
:+1:  I was able to reproduce it.

**Comment by dins2k2** [comment]
Hello All,

Thanks for the your inputs. I reinstalled the Python 2.7 and related dependent packages(pyyaml, psutil, pip). Now I am able to create clusters without any issues.

Can anyone let me know, why ccm doesn't work for Python 3.4 or the latest? ccm is not compatible for the latest version of PY? Or any new version of ccm in pipeline to compatible with new PY versions?

Thanks,
Dinesh

**Comment by ptnapoleon** [comment]
Dinesh,

I am working now to release a bugfix so that Python 3 will work on Windows.

**Comment by mambocab** [comment]
@dins2k2 Thanks for this bug report, the detail was helpful!
