### ISSUE TITLE
Add decommissioned node again to cluster - cassandra.override_decommission=true

### ISSUE THREAD

**Issue by dins2k2** [pcmanus/ccm#481]
Hello, I have decommissioned a node and stopped it. Again I tried to add it into a cluster, getting the below errror

> ERROR [main] 2016-03-23 19:10:51,865 CassandraDaemon.java:692 - Fatal configuration error
> org.apache.cassandra.exceptions.ConfigurationException: This node was decommissioned and will not rejoin the ring unless cassandra.override_decommission=true has been set, or all existing data is removed and the node is bootstrapped again
> 	at org.apache.cassandra.service.StorageService.prepareToJoin(StorageService.java:788) ~[apache-cassandra-3.0.3.jar:3.0.3]
> 	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:723) ~[apache-cassandra-3.0.3.jar:3.0.3]
> 	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:610) ~[apache-cassandra-3.0.3.jar:3.0.3]

As per the error message, to fix this, where to add the **cassandra.override_decommission=true**?
Or do I need to setup any other flags to add a decommissioned node into a cluster?

C* version : 3.0.3

Thanks,
Dinesh

**Comment by FS1360472174** [comment]
also met this issue.can set cassandra.override_decommission=true to join the node to cluster.
but what i concern about is that any difference between this and joining a new node.
cluster already works well,and the decommission node rejoin without bootstrap,so how the cluster 
deal with the existing data.and how the node rejoin the ring ?
also need help,

**Comment by ptnapoleon** [comment]
@FS1360472174, your question has nothing to do with CCM. Could you please take that to a forum for general Cassandra support, such as their IRC channel, or the user mailing list?

@dins2k2 I believe you need to set that as a JVM arg, but I am not sure. Your question is also not specific to CCM, and should be referred to a general Cassandra support forum.

**Comment by FS1360472174** [comment]
@ptnapoleon  thanks for help
