### ISSUE TITLE
Needs download mirrors

### ISSUE THREAD

**Issue by parasyte** [pcmanus/ccm#497]
Cassandra is downloaded from: https://github.com/pcmanus/ccm/blob/9dc7bea2467daa12c5b9b2fbcf64152027ac9fdc/ccmlib/repository.py#L26

But trouble is a-brewing!

![screen shot 2016-04-08 at 4 57 21 pm](https://cloud.githubusercontent.com/assets/456942/14400340/76ccf20c-fdab-11e5-8458-52c179e8d301.png)

To workaround it, I need to install git and build dependencies:

```
vagrant@blocks-kv:~$ /opt/venv-ccm/bin/ccm create -v 3.0.4 -n 3 blocks
WARN:Downloading 3.0.4 failed, due to Invalid version 3.0.4 (underlying error is: HTTP Error 503: Service Unavailable). Trying to build from git instead.
http://git-wip-us.apache.org/repos/asf/cassandra.git git:cassandra-3.0.4
Fetching Cassandra updates...
Cloning Cassandra (from local cache)
Checking out requested SHA/tag (cassandra-3.0.4)
Compiling Cassandra cassandra-3.0.4 ...
Deleted /home/vagrant/.ccm/repository/gitCOLONcassandra-3.0.4 due to error
Traceback (most recent call last):
  File "/opt/venv-ccm/bin/ccm", line 74, in <module>
    cmd.run()
  File "/opt/venv-ccm/local/lib/python2.7/site-packages/ccmlib/cmds/cluster_cmds.py", line 158, in run
    cluster = Cluster(self.path, self.name, install_dir=self.options.install_dir, version=self.options.version, verbose=True)
  File "/opt/venv-ccm/local/lib/python2.7/site-packages/ccmlib/cluster.py", line 63, in __init__
    dir, v = self.load_from_repository(version, verbose)
  File "/opt/venv-ccm/local/lib/python2.7/site-packages/ccmlib/cluster.py", line 76, in load_from_repository
    return repository.setup(version, verbose)
  File "/opt/venv-ccm/local/lib/python2.7/site-packages/ccmlib/repository.py", line 77, in setup
    clone_development(GIT_REPO, version, verbose=verbose)
  File "/opt/venv-ccm/local/lib/python2.7/site-packages/ccmlib/repository.py", line 182, in clone_development
    compile_version(git_branch, target_dir, verbose)
  File "/opt/venv-ccm/local/lib/python2.7/site-packages/ccmlib/repository.py", line 330, in compile_version
    raise CCMError("Error compiling Cassandra. Is ant installed? See %s for details" % logfile)
ccmlib.common.CCMError: Error compiling Cassandra. Is ant installed? See /home/vagrant/.ccm/repository/last.log for details
```

ccm needs to use a proper CDN for package downloads.

**Comment by stephenlb** [comment]
:+1:

**Comment by ptnapoleon** [comment]
@parasyte Is there an existing ASF CDN you are aware of that I can point to? I do not know of one, and I am not personally setting up a CDN for C* package downloads. If you are relying on CCM to have higher availability than the ASF package download site, you may be using it wrong.

**Comment by parasyte** [comment]
@ptnapoleon No, sadly I don't know of any existing CDNs for Cassandra. Even just dumping the archives into Amazon S3 would get around the issue.

Fortunately, I don't rely on ccm for anything. I just figured it would be a handy tool to get a dev cluster up quickly. It's just really frustrating when it doesn't work because ASF (of all organizations) can't even keep a bunch of disks online during maintenance.

**Comment by ptnapoleon** [comment]
Having a backup mirror would be nice, but for most usecases falling back to git is sufficient. Dumping to S3, or any other solution that we set up, would have a cost though, and that isn't something I'm prepared to incur.
