### ISSUE TITLE
'ccm' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by daiyueweng** [pcmanus/ccm#525]
Hi, I have been followed the following blog to install ccm 

http://www.datastax.com/dev/blog/ccm-2-0-and-windows

however, I got the following error when tried to run `ccm list`

`'ccm' is not recognized as an internal or external command,
operable program or batch file.`

Using `pip install ccm` shows

`Requirement already satisfied (use --upgrade to upgrade): ccm in c:\python27\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): pyYaml in c:\python27\lib\site-packages (from ccm)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in c:\python27\lib\site-packages (from ccm)`

Using `python ccm.py` shows

`Traceback (most recent call last):
  File "ccm.py", line 7, in <module>
    from ccmlib import common
ImportError: No module named 'ccmlib'`

I am using `Windows 10 X64`. I am wondering how to resolve the issue.

**Comment by sakthishanmugam02** [comment]
@daiyueweng how did you resolved this issue?
