### ISSUE TITLE
UnicodeDecodeError when pip install ccm

### ISSUE THREAD

**Issue by daiyueweng** [pcmanus/ccm#528]
Hi, I tried to install `ccm` on `Linux` (`Arch Linux 2015.02`) using `pip install ccm`, but got the following error,

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3897: ordinal not in range(128)`.

How to resolve the issue?

**Comment by mambocab** [comment]
Do you have any more stack trace than that?

**Comment by daiyueweng** [comment]
here is the full error stack:
Collecting ccm
  Using cached ccm-2.1.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0k62pp2z/ccm/setup.py", line 21, in <module>
        long_description=open(abspath(join(dirname(__file__), 'README.md'))).read(),
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3897: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0k62pp2z/ccm/

**Comment by daiyueweng** [comment]
I have installed `ccm` using `pip2` instead of `pip`.
