### ISSUE TITLE
Parameter mismatch between cluster.run_cli and node.run_cli

### ISSUE THREAD

**Issue by GregBestland** [pcmanus/ccm#553]
I think there might be a bug in the run_cli function for the cluster object.

It's calling the node's run_cli method here.

https://github.com/pcmanus/ccm/blob/master/ccmlib/cluster.py#L505
With 4 params (including self).
However node.run_cli only has 3 params including self.

https://github.com/pcmanus/ccm/blob/master/ccmlib/node.py#L826

This is going lead to a stack trace like this.

File "/usr/local/lib/python2.7/site-packages/ccmlib/cluster.py", line 504, in run_cli
    livenodes[0].run_cli(cmds, show_output, cli_options)
TypeError: run_cli() takes at most 3 arguments (4 given)

I imagine we should extend the node's run_cli method to utilize the new parameter.

**Comment by ptnapoleon** [comment]
@smccarthy788 did your most recent PR touch this?

Also, @GregBestland, you still use the cli?

**Comment by GregBestland** [comment]
@ptnapoleon I have some tests that use this for populating legacy tables.

**Comment by smccarthy788** [comment]
@ptnapoleon, no. IIRC, `show_output` was removed by cstar-97. My most recent PR removed the unused `verbose` argument from `node_cmds` call to `node.run_cli`, which had been causing a similar exception to the one above. I seem to have missed the cluster version of this call.

I think we should remove the `show_output` arg from the cluster implementation, and
```python
return livenodes[0].run_cli(cmds, show_output, cli_options)
```
which will return
```python
out, err, rc
```
allowing access to the output of cli.
