### ISSUE TITLE
Missing cassandra-env.ps1 when starting DSE cluster on Win10

### ISSUE THREAD

**Issue by alvarocorrea** [pcmanus/ccm#563]
Hello,

I am trying to create a DSE cluster on Win10 but it fails with the following error:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\my-user\\.ccm\\dse1\\node1\\resources\\cassandra\\conf\\cassandra-env.ps1' 

The file is not there so it is not a problem with permissions, I have also tried running it as administrator but I am getting the same error.
I installed ccm from the master branch and tried both Java 7 and 8.
The version of dse I'm trying to use is 4.8.7 which works for me in Ubuntu and OSX.

**Comment by ptnapoleon** [comment]
DSE isn't supported on Windows in production, and so we make no attempt to support running it on Windows via CCM.
