### ISSUE TITLE
Multiple clusters on the same machine ?

### ISSUE THREAD

**Issue by sebastianharko** [pcmanus/ccm#569]
Is it possible to start multiple clusters with ccm ? I'm on Mac OS X.

**Comment by ptnapoleon** [comment]
You can create multiple clusters, but they generally can't be running at the same time, because of bound ip/ports.

Use `ccm list` to view all your current clusters, and `ccm switch` to choose the active cluster.

**Comment by NihalHarish** [comment]
Is it not possible to change the ip/ports that is bound to clusters, to enable multiple clusters on the same machine?

**Comment by ptnapoleon** [comment]
Yes, that is possible

**Comment by dins2k2** [comment]
@NihalHarish 
You can create multiple clusters like below but you can't start all at once. Only one can be active at a time.

**Cluster1**
```
ccm create cluster1 -b -v 3.0.3 -i 127.0.0.
ccm add node1 -i 127.0.0.1 -j 7100
ccm add node2 -i 127.0.0.1 -j 7200
ccm start
ccm status        
Cluster: 'cluster1' 
------------------- 
node1: UP           
node2: UP 
```
**Cluster2**
```
ccm create cluster2 -b -v 3.0.3 -i 127.0.1. 
ccm add nd1 -i 127.0.1.1 -j 7100
ccm add nd2 -i 127.0.1.2 -j 7200
ccm start
ccm status        
Cluster: 'cluster2' 
------------------- 
nd1: UP           
nd2: UP
```
