### ISSUE TITLE
cant create a new cluster with '--jmx-port'?

### ISSUE THREAD

**Issue by delbao** [pcmanus/ccm#576]
create doesn't support this arg

so when i am using nodetool, it throws me 
nodetool: Failed to connect to '127.0.0.1:7199' - ConnectException: 'Connection refused'

**Comment by ptnapoleon** [comment]
Can you list the full commands you are using, including the nodetool call?

**Comment by delbao** [comment]
$ ccm create test -v 2.2.8 -n 3 -s

$ ~/.ccm/repository/2.2.8/bin/nodetool status
objc[20899]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
nodetool: Failed to connect to '127.0.0.1:7199' - ConnectException: 'Connection refused'.

**Comment by ptnapoleon** [comment]
It appears you didn't use `--jmx_port` in your create call? The issue you're having (at least in the above steps) is the default jmx port that nodetool points to is 7199, but the ccm nodes have 7100, 7200, and 7300 (in a three node cluster). If you use `ccm node1 nodetool status`, it will point to the correct port. If you use the normal nodetool binary, you'll have to specify the port manually.

**Comment by delbao** [comment]
@ptnapoleon 
that's actually my original question:)

   $ ccm create test -v 2.2.8 -n 3 -s --jmx-port=7199
Usage: ccm create [options] cluster_name

ccm: error: no such option: --jmx-port
