### ISSUE TITLE
Current version 2.8.2 or 2.1.3?

### ISSUE THREAD

**Issue by ilovezfs** [pcmanus/ccm#623]
Based on
https://github.com/pcmanus/ccm/releases/latest
https://github.com/pcmanus/ccm/releases

it looks like the current version is 2.1.3.

But on PyPI it appears to be 2.8.2.

What is the current stable version? If it is 2.8.2 not 2.1.3 it would be great if you could update the GitHub releases page to avoid confusion. Thanks!

**Comment by ptnapoleon** [comment]
I added a 2.8.2 github release for convenience, but I really only cut releases on pypi.
