### ISSUE TITLE
ccm does not start

### ISSUE THREAD

**Issue by ghost** [pcmanus/ccm#67]
Just installed ccm but unfortunately it does not start. Tried different versions of Cassandra (0.8.6, 1.2.5), different java versions (latest JDK6 and JDK7) but can't get it going. Used "ccm start -v" and "ccm start -v --no-wait" but ccm just hangs and produces no output. Pid file is generated for first node but the process itself does not exist (anymore). Also tried to use "python2 -m trace --trace /usr/bin/ccm start" but don't get any reasonable output.

As I am by far no Python expert, is there a good way to troubleshoot the issue?

**Comment by DanBlakeman** [comment]
Many thanks @clohfink - this was exactly my issue, your suggestion fixed it.

**Comment by zvischutz** [comment]
Many thanks @clohfink  for me too
